// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczrqW0Z6wiLcRHfkPMRnn2Eo_97k39ZM',
    appId: '1:3555334529:web:ac58e2e8cbdca962d33080',
    messagingSenderId: '3555334529',
    projectId: 'tik-tok-clone-c512e',
    authDomain: 'tik-tok-clone-c512e.firebaseapp.com',
    storageBucket: 'tik-tok-clone-c512e.firebasestorage.app',
    measurementId: 'G-CGXK0VHHQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd7ThVo__COTpPBqjiD4FAnYwwrZc35j8',
    appId: '1:3555334529:android:a0cda65361638f8fd33080',
    messagingSenderId: '3555334529',
    projectId: 'tik-tok-clone-c512e',
    storageBucket: 'tik-tok-clone-c512e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9WJr0oQbb0H6eSQeJUPp8E756BIebV_o',
    appId: '1:3555334529:ios:d4ce94ba3e739a31d33080',
    messagingSenderId: '3555334529',
    projectId: 'tik-tok-clone-c512e',
    storageBucket: 'tik-tok-clone-c512e.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );
}
